// Ejecutar desde la raiz. Solo usa PostgreSQL embebido en memoria.
import { PGlite } from '../.dart_tool/sql-test/node_modules/@electric-sql/pglite/dist/index.js';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
let checks = 0;
const exec = (s) => db.exec(s);
const one = async (s, p = []) => (await db.query(s, p)).rows[0];
async function reject(work, pattern) {
  await assert.rejects(work, pattern); checks++;
}
try {
  await exec(readFileSync('.dart_tool/sql-test/fixture.sql', 'utf8').replace(/^\uFEFF/, ''));
  const migration = readFileSync('sql/pruebas/055_edicion_admin.sql', 'utf8');
  const patch = readFileSync('sql/pruebas/057_corregir_total_sin_lote.sql', 'utf8').replace(/^\uFEFF/, '');
  await exec(migration);
  await exec(patch);
  await exec(migration); await exec(patch); await exec(patch); checks++; // idempotencia real
  const adminAuth = '00000000-0000-0000-0000-000000000001';
  const workerAuth = '00000000-0000-0000-0000-000000000002';
  await db.query(`insert into usuarios(nombre,numero_usuario,rol,auth_id) values
    ('ADMIN TEST','9901','admin',$1),('WORKER TEST','9902','logistica',$2)`, [adminAuth,workerAuth]);
  const op = (await one("insert into ordenes_produccion(numero_op,cliente) values('TEST-ADMIN','CLIENTE TEST') returning id")).id;
  const item = (await one("insert into items_orden(orden_id,codigo,talla,descripcion,cantidad_pedida) values($1,'TEST-COD','M','TEST',10) returning id", [op])).id;
  await db.query("insert into items_orden(orden_id,codigo,talla,descripcion,cantidad_pedida) values($1,'TEST-COD-S','S','TEST',10)",[op]);
  const loc = (await one("insert into ubicaciones(codigo) values('TEST-A1') returning id")).id;
  const loc2 = (await one("insert into ubicaciones(codigo) values('TEST-A2') returning id")).id;
  const lote = (await one("insert into lotes(numero,operario_nombre) values('TEST-LOTE','TEST') returning id")).id;
  const li = (await one("insert into lote_items(lote_id,item_orden_id,cantidad_enviada,cantidad_recibida,estado) values($1,$2,6,6,'recibido_conforme') returning id", [lote,item])).id;
  await db.query(`insert into movimientos(tipo,item_orden_id,cantidad,lote_id,lote_item_id,ubicacion_id)
    values('entrega_produccion',$1,6,$2,$3,null),('recepcion',$1,6,$2,$3,$4),('despacho',$1,2,null,null,$4)`, [item,lote,li,loc]);
  const originals = (await db.query('select * from movimientos order by id')).rows;
  await exec('SET ROLE authenticated');
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[adminAuth]);
  const ctx = async () => (await one('select admin_contexto_edicion($1) as data',[item])).data;
  const edit = async (field,value,save=true,opts={}) => {
    const version = opts.version ?? (await ctx()).version;
    return (await one('select admin_editar_kardex($1,$2,$3::jsonb,$4,$5,$6,$7,$8) as data',
      [item,field,JSON.stringify(value),opts.reason ?? 'Corrección de prueba',version,'line' in opts ? opts.line : li,opts.loc ?? loc,save])).data;
  };
  const initial = await ctx();
  assert.equal(initial.valores.producido,6); checks++;
  const preview = await edit('cantidad_pedida',20,false);
  assert.equal(preview.despues.cantidad_pedida,20);
  assert.equal((await ctx()).valores.cantidad_pedida,10);
  assert.equal((await ctx()).historial.length,0); checks++;
  await edit('cantidad_pedida',20);
  let c = await ctx();
  assert.equal(c.valores.cantidad_pedida,20);
  assert.equal(c.valores.producido,6);
  assert.equal(c.valores.recibido,6); checks++;
  await reject(() => edit('cantidad_pedida',30,true,{version:initial.version}),/fila cambió/);
  await reject(() => edit('cantidad_pedida',1),/incompatibles/);
  await reject(() => edit('cantidad_pedida',25,true,{reason:''}),/motivo/);
  await edit('producido',8);
  assert.equal((await one('select cantidad_enviada,estado from lote_items where id=$1',[li])).cantidad_enviada,6);
  assert.equal((await one('select estado from lote_items where id=$1',[li])).estado,'recibido_conforme'); checks++;
  await edit('recibido',5);
  assert.equal((await one('select cantidad_recibida,estado from lote_items where id=$1',[li])).estado,'en_transito'); checks++;
  await edit('recibido',4);
  assert.equal((await ctx()).valores.recibido,4); checks++;
  await reject(() => edit('recibido',1),/incompatibles/);
  await reject(() => edit('recibido',3,true,{loc:loc2}),/Stock insuficiente|registrada/);
  await edit('despachado',3);
  await edit('despachado',1);
  assert.equal((await ctx()).valores.despachado,1); checks++;
  await reject(() => edit('despachado',0,true,{loc:loc2}),/registrada/);
  await edit('pendiente_reproceso',1);
  c = await ctx();
  assert.equal(c.valores.producido,7); assert.equal(c.valores.recibido,3);
  assert.equal(c.valores.pendiente_reproceso,1); checks++;
  await reject(() => one('select despachar($1,6,$2)',[item,loc]),/Stock insuficiente/);
  await edit('pendiente_reproceso',0);
  assert.equal((await ctx()).valores.recibido,4); checks++;
  await edit('cliente','CLIENTE CORREGIDO');
  assert.equal((await one('select count(*)::int n from vista_kardex where cliente=$1',['CLIENTE CORREGIDO'])).n,2); checks++;
  await edit('fecha_ultima_entrega','2040-10-02');
  assert.equal((await ctx()).valores.fecha_ultima_entrega,'2040-10-02'); checks++;
  await edit('fecha_ultima_entrega',null);
  assert.equal((await ctx()).valores.fecha_ultima_entrega,null); checks++;
  await reject(() => edit('fecha_esperada_produccion','2026-02-30'),/out of range/);
  await reject(() => edit('estado','Completado'),/Campo no editable/);
  await reject(() => edit('cantidad_pedida',2.5),/entera/);
  await reject(() => edit('cantidad_pedida',-1),/entera/);
  await reject(() => edit('cantidad_pedida',null),/entera/);
  // Correcciones y movimientos originales permanecen consultables e inmutables para authenticated.
  const originalIds = originals.map(x=>x.id);
  const saved = (await db.query('select * from movimientos where id=any($1::uuid[]) order by id',[originalIds])).rows;
  assert.deepEqual(saved,originals); checks++;
  await reject(() => db.query('insert into admin_correcciones default values'),/permission denied/);
  const correction = (await one('select id from admin_correcciones limit 1')).id;
  await reject(() => db.query("insert into movimientos(tipo,item_orden_id,cantidad,admin_correccion_id) values('entrega_produccion',$1,-1,$2)",[item,correction]),/row-level security/);
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[workerAuth]);
  await reject(() => ctx(),/exclusivo/);
  await reject(() => edit('cantidad_pedida',30,true,{version:'x'}),/exclusivo/);
  await db.query("update usuarios set rol='admin' where auth_id=$1",[workerAuth]);
  assert.equal((await one('select rol from usuarios where auth_id=$1',[workerAuth])).rol,'logistica'); checks++;
  assert.equal((await db.query('select * from admin_correcciones')).rows.length,0); checks++;
  // Las RPC ordinarias siguen funcionando tras los nuevos permisos.
  const nuevo = (await one('select crear_lote($1::jsonb,$2) as data',[
    JSON.stringify([{item_orden_id:item,cantidad:2}]),'WORKER TEST'])).data;
  const nuevaLinea = (await one('select id from lote_items where lote_id=$1',[nuevo.id])).id;
  await one('select recibir_lote_item($1,1,$2,$3,$4)',[nuevaLinea,loc,'Prueba parcial','WORKER TEST']);
  assert.equal((await one('select estado from lote_items where id=$1',[nuevaLinea])).estado,'en_transito'); checks++;
  await one('select recibir_lote_item($1,1,$2,$3,$4)',[nuevaLinea,loc,'Prueba completa','WORKER TEST']);
  assert.equal((await one('select estado from lote_items where id=$1',[nuevaLinea])).estado,'recibido_conforme'); checks++;
  await one('select despachar($1,1,$2)',[item,loc]); checks++;
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[adminAuth]);
  const producido = (await ctx()).valores.producido;
  const nuevoAdmin = await edit('producido',producido+1,true,{line:null});
  assert.equal(nuevoAdmin.despues.producido,producido+1); checks++;
  const datosAntesRepetir = (await db.query('select * from movimientos order by id')).rows;
  const auditoriaAntesRepetir = (await db.query('select * from admin_correcciones order by id')).rows;
  const saldosAntesRepetir = (await ctx()).valores;
  await exec('RESET ROLE');
  await exec(migration);
  await exec(patch);
  await exec('SET ROLE authenticated');
  assert.deepEqual((await db.query('select * from movimientos order by id')).rows,datosAntesRepetir);
  assert.deepEqual((await db.query('select * from admin_correcciones order by id')).rows,auditoriaAntesRepetir);
  assert.deepEqual((await ctx()).valores,saldosAntesRepetir); checks++;
  // Corrección del total 28 -> 20: lotes y recepciones intactos, sin lote requerido.
  await exec('RESET ROLE');
  const caso = (await one("insert into items_orden(orden_id,codigo,talla,descripcion,cantidad_pedida) values($1,'CASO-28-20','M','CORRECCION HUMANA',40) returning id",[op])).id;
  const loteCaso = (await one("insert into lotes(numero,operario_nombre) values('CASO-107','TEST') returning id")).id;
  const lineaCaso = (await one("insert into lote_items(lote_id,item_orden_id,cantidad_enviada,cantidad_recibida,estado) values($1,$2,25,25,'recibido_conforme') returning id",[loteCaso,caso])).id;
  await db.query("insert into movimientos(tipo,item_orden_id,cantidad,lote_id,lote_item_id,ubicacion_id) values ('entrega_produccion',$1,25,$2,$3,null),('entrega_produccion',$1,3,null,null,null),('recepcion',$1,25,$2,$3,$4)",[caso,loteCaso,lineaCaso,loc]);
  await exec('SET ROLE authenticated');
  const contextoCaso = (await one('select admin_contexto_edicion($1) as data',[caso])).data;
  const propuestaCaso = (await one("select admin_editar_kardex($1,'producido','20'::jsonb,'Error humano',$2,$3,null,false) as data",[caso,contextoCaso.version,lineaCaso])).data;
  assert.equal(propuestaCaso.despues.producido,20); assert.equal(propuestaCaso.despues.recibido,25);
  await one("select admin_editar_kardex($1,'producido','20'::jsonb,'Error humano',$2,$3,null,true)",[caso,contextoCaso.version,lineaCaso]);
  const finCaso = await one('select producido,recibido,cantidad_pedida-producido pendiente from vista_kardex where item_orden_id=$1',[caso]);
  assert.deepEqual(finCaso,{producido:20,recibido:25,pendiente:20});
  const finLote = await one('select cantidad_enviada,cantidad_recibida,estado from lote_items where id=$1',[lineaCaso]);
  assert.deepEqual(finLote,{cantidad_enviada:25,cantidad_recibida:25,estado:'recibido_conforme'});
  assert.equal((await one('select cantidad from vista_stock_ubicacion_detalle where item_orden_id=$1',[caso])).cantidad,25); checks++;
  const lotesIntactos = (await db.query('select * from lotes order by id')).rows;
  const lineasIntactas = (await db.query('select * from lote_items order by id')).rows;
  for (const total of [10,2,0,12]) {
    const ver = (await one('select admin_contexto_edicion($1) as data',[caso])).data.version;
    await one("select admin_editar_kardex($1,'producido',$2::jsonb,'Total corregido',$3,null,null,true)",[caso,JSON.stringify(total),ver]);
    const estado = await one('select producido,recibido,cantidad_pedida-producido pendiente from vista_kardex where item_orden_id=$1',[caso]);
    assert.deepEqual(estado,{producido:total,recibido:25,pendiente:40-total});
    const ajuste = await one('select lote_id,lote_item_id from movimientos where item_orden_id=$1 and admin_correccion_id is not null order by fecha desc limit 1',[caso]);
    assert.deepEqual(ajuste,{lote_id:null,lote_item_id:null}); checks++;
  }
  assert.deepEqual((await db.query('select * from lotes order by id')).rows,lotesIntactos);
  assert.deepEqual((await db.query('select * from lote_items order by id')).rows,lineasIntactas); checks++;

  const borrarSql = readFileSync('sql/pruebas/058_borrado_logico_admin.sql','utf8');
  await exec('RESET ROLE');
  await exec(borrarSql);
  await exec('SET ROLE authenticated');
  const movimientosAntes = (await db.query('select * from movimientos order by id')).rows;
  const filasAntes = (await db.query('select id from items_orden order by id')).rows;
  const borrarCtx = (await one('select admin_contexto_edicion($1) as data',[caso])).data;
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[workerAuth]);
  await reject(() => one("select admin_eliminar_linea($1,$2,'Duplicado')",[caso,borrarCtx.version]),/administrador/);
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[adminAuth]);
  await reject(() => one("select admin_eliminar_linea($1,'vieja','Duplicado')",[caso]),/fila cambio/);
  await reject(() => one("select admin_eliminar_linea($1,$2,' ')",[caso,borrarCtx.version]),/motivo/);
  await one("select admin_eliminar_linea($1,$2,'Duplicado')",[caso,borrarCtx.version]);
  assert.ok((await one('select admin_eliminado_en from vista_kardex where item_orden_id=$1',[caso])).admin_eliminado_en); checks++;
  assert.deepEqual((await db.query('select id from items_orden order by id')).rows,filasAntes);
  assert.deepEqual((await db.query('select * from movimientos order by id')).rows,movimientosAntes);
  assert.deepEqual((await db.query('select * from lote_items order by id')).rows,lineasIntactas);
  assert.equal((await one('select count(*)::int as n from items_orden where admin_eliminado_en is not null')).n,1); checks++;
  assert.equal((await one("select count(*)::int as n from admin_correcciones where campo='admin_eliminado_en' and item_id=$1",[caso])).n,1); checks++;
  await reject(() => one("select admin_eliminar_linea($1,$2,'Duplicado')",[caso,borrarCtx.version]),/fila cambio/);
  await exec('RESET ROLE');
  await exec(borrarSql);
  await exec('SET ROLE authenticated');
  assert.ok((await one('select admin_eliminado_en from items_orden where id=$1',[caso])).admin_eliminado_en); checks++;

  await exec('RESET ROLE');
  const importSql = readFileSync('sql/pruebas/059_importar_tabla_admin.sql','utf8');
  await exec(importSql); await exec(importSql);
  await exec('SET ROLE authenticated');
  const exportar = async () => (await one('select admin_exportar_kardex() as data')).data;
  const archivo = await exportar();
  const filasImport = archivo.filas.map(f => Object.fromEntries(['item_orden_id','numero_op','descripcion','codigo','talla','cliente','oc','observacion_op','cantidad_pedida','producido','recibido','despachado','pendiente_reproceso','fecha_ultima_entrega','fecha_esperada_logistica'].map(k => [k,f[k]])));
  filasImport.forEach(f => f.ubicacion_ajuste='');
  const importar = (rows, version, confirmar=false) => one('select admin_importar_kardex($1,$2,$3::jsonb,$4,$5) as data',['logistica',version,JSON.stringify(rows),'Prueba Excel',confirmar]);
  const sinCambios = (await importar(filasImport,archivo.version)).data;
  assert.equal(sinCambios.modificadas,0); checks++;
  const objetivo = filasImport[0];
  objetivo.cantidad_pedida += 10;
  const antesImport = await exportar();
  const previewImport = (await importar(filasImport,archivo.version)).data;
  assert.equal(previewImport.modificadas,1);
  assert.equal(previewImport.guardado,false);
  assert.deepEqual(await exportar(),antesImport); checks++;
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[workerAuth]);
  await reject(() => importar(filasImport,archivo.version,true),/administrador/);
  await reject(() => exportar(),/administrador/);
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[adminAuth]);
  await reject(() => importar([...filasImport,filasImport[0]],archivo.version,true),/duplicados/);
  await reject(() => importar(filasImport.slice(1),archivo.version,true),/Faltan/);
  assert.deepEqual(await exportar(),antesImport); checks++;
  const invalido = structuredClone(filasImport); invalido[invalido.length-1].cantidad_pedida=0;
  await reject(() => importar(invalido,archivo.version,true),/incompatibles/);
  assert.deepEqual(await exportar(),antesImport); checks++;
  await importar(filasImport,archivo.version,true);
  assert.equal((await one('select cantidad_pedida from items_orden where id=$1',[objetivo.item_orden_id])).cantidad_pedida,objetivo.cantidad_pedida); checks++;
  await reject(() => importar(filasImport,archivo.version,true),/cambiaron/);
  assert.equal((await one('select count(*)::int as n from admin_importaciones')).n,1); checks++;
  assert.deepEqual((await db.query('select * from lote_items order by id')).rows,lineasIntactas); checks++;

  const filasDe = (exportado, vista='logistica') => exportado.filas.map(f => ({...Object.fromEntries([
    'item_orden_id','numero_op','descripcion','codigo','talla','cliente','oc','observacion_op','cantidad_pedida','producido','pendiente_reproceso','fecha_ultima_entrega',
    ...(vista==='logistica'?['recibido','despachado','fecha_esperada_logistica']:['fecha_esperada_produccion'])
  ].map(k => [k,f[k]])),ubicacion_ajuste:''}));
  let exp = await exportar(); let filasMas = filasDe(exp);
  const ajusteExcel = filasMas.find(f => f.item_orden_id===item);
  ajusteExcel.recibido+=2; ajusteExcel.despachado+=1; ajusteExcel.pendiente_reproceso+=1;
  ajusteExcel.cantidad_pedida=Math.max(ajusteExcel.cantidad_pedida,ajusteExcel.despachado);
  await reject(() => importar(filasMas,exp.version,true),/UBICACION/);
  ajusteExcel.ubicacion_ajuste='TEST-A1';
  await importar(filasMas,exp.version,true);
  let realExcel = await one('select producido,recibido,despachado,pendiente_reproceso from vista_kardex where item_orden_id=$1',[item]);
  assert.deepEqual(realExcel,Object.fromEntries(Object.keys(realExcel).map(k=>[k,ajusteExcel[k]]))); checks++;
  assert.deepEqual((await db.query('select * from lote_items order by id')).rows,lineasIntactas); checks++;
  exp = await exportar(); filasMas = filasDe(exp);
  filasMas.push({...filasMas[0],item_orden_id:'',numero_op:'NUEVA-EXCEL',codigo:'NEW',talla:'XS',cliente:'NUEVO',cantidad_pedida:10,producido:4,recibido:3,despachado:1,pendiente_reproceso:1,ubicacion_ajuste:'TEST-A1'});
  const nuevaPreview=(await importar(filasMas,exp.version)).data;
  assert.equal(nuevaPreview.nuevas,1); assert.equal((await exportar()).version,exp.version); checks++;
  await importar(filasMas,exp.version,true);
  assert.equal((await one("select recibido-despachado as stock from vista_kardex where numero_op='NUEVA-EXCEL'")).stock,2); checks++;
  exp=await exportar(); const filasProd=filasDe(exp,'produccion');
  filasProd.find(f=>f.item_orden_id===item).producido=0;
  await one('select admin_importar_kardex($1,$2,$3::jsonb,$4,true)',['produccion',exp.version,JSON.stringify(filasProd),'Corregir total']);
  const produccionReal=await one('select producido,recibido,despachado,pendiente_reproceso from vista_kardex where item_orden_id=$1',[item]);
  assert.deepEqual(produccionReal,{...realExcel,producido:0}); checks++;
  exp=await exportar(); filasMas=filasDe(exp);
  assert.equal((await importar(filasMas,exp.version)).data.modificadas,0); checks++;
  filasMas[0].campo_desconocido=123;
  await reject(() => importar(filasMas,exp.version,true),/no permitida/);
  for (const original of originals) assert.deepEqual(await one('select * from movimientos where id=$1',[original.id]),original);
  checks++;

  await exec('RESET ROLE');
  await exec("CREATE TABLE IF NOT EXISTS auth.users(id uuid PRIMARY KEY,email text,raw_app_meta_data jsonb DEFAULT '{}'::jsonb)");
  const catalogSql=readFileSync('sql/pruebas/060_administrar_catalogos.sql','utf8');
  await exec(catalogSql); await exec(catalogSql);
  await exec('SET ROLE authenticated');
  const listarCat=async(tipo)=>(await one('select admin_catalogos_listar($1) as data',[tipo])).data;
  const guardarCat=async(tipo,row,nombre,activo)=>(await one('select admin_catalogos_guardar($1,$2,$3,$4,$5) as data',[tipo,row?.id??null,nombre,activo,row?.version??null])).data;
  const guardarUsr=async(row,rol,activo)=>(await one('select admin_usuario_guardar($1,$2,$3,$4,$5) as data',[row.id,row.nombre,rol,activo,row.version])).data;
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[workerAuth]);
  await reject(()=>listarCat('usuarios'),/administrador/);
  await reject(()=>guardarCat('personal_logistica',null,'PERSONA',true),/administrador/);
  await reject(()=>one("insert into personal_logistica(nombre) values('DIRECTO')"),/permission denied/);
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[adminAuth]);
  await guardarCat('personal_logistica',null,'PERSONA TYPO',true);
  let persona=(await listarCat('personal_logistica')).find(p=>p.nombre==='PERSONA TYPO');
  const personaId=persona.id;
  await guardarCat('personal_logistica',persona,'PERSONA CORRECTA',true);
  await reject(()=>guardarCat('personal_logistica',persona,'VIEJO',true),/cambio/);
  persona=(await listarCat('personal_logistica')).find(p=>p.id===personaId);
  await guardarCat('personal_logistica',persona,persona.nombre,false);
  await reject(()=>one("select agregar_personal_logistica('PERSONA CORRECTA')"),/inactivo/);
  await reject(()=>guardarCat('personal_logistica',null,' persona correcta ',true),/Ya existe/);
  persona=(await listarCat('personal_logistica')).find(p=>p.id===personaId);
  await guardarCat('personal_logistica',persona,persona.nombre,true);
  assert.equal((await one("select agregar_personal_logistica('persona correcta') as data")).data.id,personaId); checks++;
  await guardarCat('ubicaciones',null,'ESTANTE NUEVO',true);
  let estante=(await listarCat('ubicaciones')).find(p=>p.codigo==='ESTANTE NUEVO');
  await guardarCat('ubicaciones',estante,estante.codigo,false);
  await reject(()=>one('select despachar($1,1,$2)',[item,estante.id]),/inactivo/);
  const ocupado=(await listarCat('ubicaciones')).find(p=>p.id===loc);
  await reject(()=>guardarCat('ubicaciones',ocupado,ocupado.codigo,false),/existencias/);
  await guardarCat('ubicaciones',ocupado,'ESTANTE RENOMBRADO',true);
  assert.ok((await one("select count(*)::int n from vista_stock_ubicacion_detalle where ubicacion_codigo='ESTANTE RENOMBRADO'")).n>0); checks++;
  let cuentas=await listarCat('usuarios');
  let miCuenta=cuentas.find(p=>p.auth_id===adminAuth);
  let workerCuenta=cuentas.find(p=>p.auth_id===workerAuth);
  await reject(()=>guardarUsr(miCuenta,'produccion',true),/al menos un administrador/);
  await reject(()=>guardarUsr(miCuenta,'admin',false),/propia cuenta/);
  await guardarUsr(workerCuenta,'produccion',false);
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[workerAuth]);
  assert.equal((await one('select count(*)::int n from items_orden')).n,0);
  assert.equal((await one('select count(*)::int n from vista_kardex')).n,0); checks++;
  await reject(()=>one("select crear_lote('[]'::jsonb,'TEST',null)"),/inactiva/);
  await reject(()=>one("select agregar_personal_logistica('NUEVO')"),/inactiva/);
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[adminAuth]);
  workerCuenta=(await listarCat('usuarios')).find(p=>p.auth_id===workerAuth);
  await guardarUsr(workerCuenta,'logistica',true);
  await exec('RESET ROLE');
  const altaAuth='00000000-0000-0000-0000-000000000003';
  await db.query("insert into auth.users(id,email,raw_app_meta_data) values($1,'9903@orbiloq.local','{\"orbiloq_alta_catalogo\":true}'::jsonb)",[altaAuth]);
  await exec('SET ROLE authenticated');
  await reject(()=>one('select admin_usuario_registrar($1,$2,$3,$4,$5)',[adminAuth,altaAuth,'9903','ALTA','produccion']),/permission denied/);
  await exec('RESET ROLE'); await exec('SET ROLE service_role');
  assert.equal((await one("select admin_usuario_alta_pendiente('9903') id")).id,altaAuth); checks++;
  await reject(()=>one('select admin_usuario_registrar($1,$2,$3,$4,$5)',[workerAuth,altaAuth,'9903','ALTA','produccion']),/administrador/);
  const alta=(await one('select admin_usuario_registrar($1,$2,$3,$4,$5) data',[adminAuth,altaAuth,'9903','ALTA','produccion'])).data;
  const reintento=(await one('select admin_usuario_registrar($1,$2,$3,$4,$5) data',[adminAuth,altaAuth,'9903','ALTA','produccion'])).data;
  assert.deepEqual(alta,reintento); checks++;
  await exec('RESET ROLE'); await exec(catalogSql); await exec('SET ROLE authenticated');
  assert.equal((await listarCat('usuarios')).filter(p=>p.numero_usuario==='9903').length,1); checks++;
  assert.ok((await one('select count(*)::int n from admin_catalogos_historial')).n>=7); checks++;
  for (const original of originals) assert.deepEqual(await one('select * from movimientos where id=$1',[original.id]),original); checks++;

  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[workerAuth]);
  assert.equal((await one("select agregar_personal_logistica('PERSONA OPERATIVA') data")).data.nombre,'PERSONA OPERATIVA');checks++;
  await reject(()=>one("select crear_lote('[]'::jsonb,'TEST',null)"),/requiere Produccion/);
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[adminAuth]);
  workerCuenta=(await listarCat('usuarios')).find(p=>p.auth_id===workerAuth);
  await guardarUsr(workerCuenta,'produccion',true);
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[workerAuth]);
  await reject(()=>one('select despachar($1,1,$2)',[item,loc]),/requiere Logistica/);
  const loteOperativo=await one("select crear_lote($1::jsonb,'TEST','LOTE-ACTIVO-V60') data",[JSON.stringify([{item_orden_id:item,cantidad:1}])]);
  assert.ok(loteOperativo.data);checks++;
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[adminAuth]);
  // Duplicados historicos por capitalizacion pueden desactivarse sin fusionar ni borrar.
  await exec('RESET ROLE');
  await exec("insert into personal_produccion(nombre) values('DUPLICADO'),('duplicado')");
  await exec('SET ROLE authenticated');
  const duplicada=(await listarCat('personal_produccion')).find(p=>p.nombre==='duplicado');
  await guardarCat('personal_produccion',duplicada,duplicada.nombre,false);
  assert.equal((await listarCat('personal_produccion')).filter(p=>p.nombre.toLowerCase()==='duplicado').length,2);checks++;
  await exec('RESET ROLE');
  const historialAntes61=(await db.query('select * from lotes order by id')).rows;
  const actorSql=readFileSync('sql/pruebas/061_operario_desde_sesion.sql','utf8');
  await exec(actorSql); await exec(actorSql);
  assert.deepEqual((await db.query('select * from lotes order by id')).rows,historialAntes61);checks++;
  const nuevoItem=(await one("insert into items_orden(orden_id,codigo,talla,descripcion,cantidad_pedida) values($1,'ACTOR61','M','Actor',100) returning id",[op])).id;
  await exec("insert into usuarios(nombre,numero_usuario,rol) values('ADMIN TEST','9919','produccion')");
  await exec("insert into personal_logistica(nombre,activo) values('ADMIN TEST',false)");
  await exec('SET ROLE authenticated');
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[adminAuth]);
  await one("select crear_lote($1::jsonb,'NOMBRE FALSO','LOTE-ACTOR-61')",[JSON.stringify([{item_orden_id:nuevoItem,cantidad:3}])]);
  const registrado=await one("select l.operario_nombre,u.auth_id from lotes l join usuarios u on u.id=l.operario_id where l.numero='LOTE-ACTOR-61'");
  assert.equal(registrado.operario_nombre,'ADMIN TEST');assert.equal(registrado.auth_id,adminAuth);checks++;
  const lineaActor61=await one("select li.id from lote_items li join lotes l on l.id=li.lote_id where l.numero='LOTE-ACTOR-61'");
  await one("select recibir_lote_item($1,1,$2,'','OTRA PERSONA')",[lineaActor61.id,loc]);
  assert.equal((await one('select recibido_por from lote_items where id=$1',[lineaActor61.id])).recibido_por,'ADMIN TEST');checks++;
  await db.query("select set_config('request.jwt.claim.sub','',false)");
  await reject(()=>one("select wms_nombre_actor()"),/cuenta activa/);
  await exec('RESET ROLE');
  const movimientosAntes62=(await db.query('select * from movimientos order by id')).rows;
  const reportesSql=readFileSync('sql/pruebas/062_reportes_admin.sql','utf8');
  await exec(reportesSql); await exec(reportesSql);
  assert.deepEqual((await db.query('select * from movimientos order by id')).rows,movimientosAntes62);checks++;
  await exec('SET ROLE authenticated');
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[workerAuth]);
  await reject(()=>one("select admin_reporte_resumen()"),/administrador/);
  await reject(()=>one("select admin_reporte_pagina('movimientos')"),/administrador/);
  await reject(()=>one("select * from admin_reporte_movimientos_interno"),/permission denied/);
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[adminAuth]);
  const resumen62=(await one('select admin_reporte_resumen() datos')).datos;
  assert.ok(resumen62.op_activas>=0); checks++;
  const datos62=(await one("select admin_reporte_pagina('movimientos') datos")).datos;
  assert.equal(datos62.length,movimientosAntes62.length);checks++;
  assert.ok(datos62.every(f=>f.datos_crudos.id&&f.registro&&f.op));checks++;
  for (const tipo of ['nc','auditoria']) {
    assert.ok(Array.isArray((await one('select admin_reporte_pagina($1) datos',[tipo])).datos));checks++;
  }
  await reject(()=>one("select admin_reporte_pagina('usuarios')"),/inválido/);
  await exec('RESET ROLE');
  await db.query("insert into movimientos(tipo,item_orden_id,cantidad,fecha) select 'entrega_produccion',$1,1,'2026-01-01'::timestamptz from generate_series(1,1001)",[nuevoItem]);
  await exec('SET ROLE authenticated');
  const pag1=(await one("select admin_reporte_pagina('movimientos','','2100-01-01') datos")).datos;
  const pag2=(await one("select admin_reporte_pagina('movimientos',$1,'2100-01-01') datos",[pag1.at(-1).registro])).datos;
  assert.equal(pag1.length,1000);assert.equal(pag1.length+pag2.length,movimientosAntes62.length+1001);checks++;
  assert.equal(new Set([...pag1,...pag2].map(f=>f.registro)).size,pag1.length+pag2.length);checks++;
  const previo62=(await one('select admin_reporte_resumen() datos')).datos;
  await exec('RESET ROLE');
  const opMetricas62=(await one("insert into ordenes_produccion(numero_op,cliente,fecha_esperada_produccion,fecha_esperada_logistica) values('METRICAS-62','Cliente Métricas','2000-01-01','2000-01-01') returning id")).id;
  const lineasMetricas62=(await db.query("insert into items_orden(orden_id,codigo,talla,descripcion,cantidad_pedida) values($1,'METRICAS','M','Métricas',10),($1,'METRICAS','S','Métricas',10) returning id",[opMetricas62])).rows;
  await db.query("insert into movimientos(tipo,item_orden_id,cantidad) values('devolucion_produccion',$1,2)",[lineasMetricas62[0].id]);
  const despues62=(await one('select admin_reporte_resumen() datos')).datos;
  assert.equal(despues62.op_activas,previo62.op_activas+1);assert.equal(despues62.op_atrasadas,previo62.op_atrasadas+1);assert.equal(despues62.op_no_conforme,previo62.op_no_conforme+1);checks++;
  await db.query('update items_orden set admin_eliminado_en=now() where orden_id=$1',[opMetricas62]);
  const ocultas62=(await one('select admin_reporte_resumen() datos')).datos;
  assert.equal(ocultas62.op_activas,previo62.op_activas);assert.equal(ocultas62.op_no_conforme,previo62.op_no_conforme);checks++;
  const causal62=(await one("insert into causales_devolucion(nombre) values('CAUSAL REPORTES') returning id")).id;
  await db.query("insert into devoluciones_produccion(item_orden_id,causal_id,cantidad,operario_nombre) values($1,$2,2,'ANA REPORTE')",[lineasMetricas62[0].id,causal62]);
  await db.query("insert into no_conformes_aliados(item_orden_id,causal_id,cantidad_solicitada,usuario_produccion_solicitud_nombre,persona_aliado_entrega) values($1,$2,3,'ANA REPORTE','ALIADO')",[lineasMetricas62[0].id,causal62]);
  const nc62=(await one("select admin_reporte_pagina('nc') datos")).datos.filter(f=>f.causal==='CAUSAL REPORTES');
  assert.equal(nc62.length,2);assert.equal(nc62.reduce((n,f)=>n+f.cantidad,0),5);assert.deepEqual(new Set(nc62.map(f=>f.origen)),new Set(['Logística','Aliados']));checks++;
  const antes63=(await db.query('select to_jsonb(m) fila from movimientos m order by id')).rows.map(r=>r.fila);
  const sql63=readFileSync('sql/pruebas/063_despacho_por_oc.sql','utf8');
  await exec(sql63); await exec(sql63);
  const loc63=(await one("insert into ubicaciones(codigo) values('OC63-A') returning id")).id;
  const locB63=(await one("insert into ubicaciones(codigo) values('OC63-B') returning id")).id;
  assert.deepEqual((await db.query('select to_jsonb(m)-\'despacho_oc_id\' fila from movimientos m order by id')).rows.map(r=>r.fila),antes63);checks++;
  const op63=(await one("insert into ordenes_produccion(numero_op,cliente) values('DESPACHO63','CLIENTE63') returning id")).id;
  const item63=(await one("insert into items_orden(orden_id,codigo,talla,descripcion,cantidad_pedida,oc) values($1,'C63','M','Prenda63',10,'OC63') returning id",[op63])).id;
  const sinStock63=(await one("insert into items_orden(orden_id,codigo,talla,descripcion,cantidad_pedida,oc) values($1,'C63','S','Prenda63',10,'OC63') returning id",[op63])).id;
  await db.query("insert into movimientos(tipo,item_orden_id,cantidad,ubicacion_id) values('recepcion',$1,4,$2),('recepcion',$1,6,$3)",[item63,loc63,locB63]);
  const plan63=[{item_id:item63,ubicacion:'OC63-A',cantidad:4},{item_id:item63,ubicacion:'OC63-B',cantidad:6}];
  const desp63=async (lineas=plan63,key='solicitud63',cliente='CLIENTE63')=>(await one('select despachar_oc($1,$2,$3,$4::jsonb) datos',[key,cliente,'OC63',JSON.stringify(lineas)])).datos;
  await exec('SET ROLE authenticated');
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[workerAuth]);
  await reject(()=>desp63(),/Logística/);
  await reject(()=>one('select historial_despachos_oc()'),/Logística/);
  await db.query("select set_config('request.jwt.claim.sub',$1,false)",[adminAuth]);
  await reject(()=>desp63(plan63,'cliente-malo','OTRO'),/pertenecer/);
  await reject(()=>desp63([{...plan63[0],cantidad:11}]),/pendiente/);
  await reject(()=>desp63([{...plan63[0],cantidad:5}]),/Stock insuficiente/);
  await reject(()=>desp63([{...plan63[0],cantidad:0}]),/positiva/);
  await reject(()=>desp63([...plan63,{item_id:sinStock63,ubicacion:'OC63-A',cantidad:1}]),/Stock total/);
  await exec('RESET ROLE');
  assert.equal((await one('select count(*)::int n from despachos_oc')).n,0);checks++;
  assert.equal((await one("select count(*)::int n from movimientos where item_orden_id=$1 and tipo='despacho'",[item63])).n,0);checks++;
  await exec('SET ROLE authenticated');
  const guardado63=await desp63();
  const repetido63=await desp63();
  assert.equal(guardado63.id,repetido63.id);assert.equal(repetido63.repetido,true);checks++;
  await reject(()=>desp63([{...plan63[0],cantidad:1}]),/otro despacho/);
  await reject(()=>desp63(plan63,'nuevo-despacho'),/pendiente/);
  const hist63=(await one('select historial_despachos_oc() datos')).datos;
  const detalle63=hist63.filter(r=>r.despacho_oc_id===guardado63.id);
  assert.equal(detalle63.length,2);assert.equal(detalle63.reduce((n,r)=>n+r.cantidad,0),10);checks++;
  assert.ok(detalle63.every(r=>r.persona==='ADMIN TEST'&&r.oc==='OC63'));checks++;
  assert.ok(hist63.some(r=>!r.despacho_oc_id));checks++;
  await reject(()=>one('select * from despachos_oc'),/permission denied/);
  await exec('RESET ROLE');
  const blank63=(await one("insert into items_orden(orden_id,codigo,talla,descripcion,cantidad_pedida,oc) values($1,'BLANK','M','Sin OC',7,'') returning id",[op63])).id;
  const tallas63=[{identificador_orden:'DESPACHO63',codigo:'BLANK',talla:'M',cantidad:'99',oc:'OC63'},{identificador_orden:'DESPACHO63',codigo:'C63',talla:'M',cantidad:'99',oc:'NO-REEMPLAZAR'}];
  await exec('SET ROLE authenticated');
  await one("select importar_ordenes_produccion('[]',$1::jsonb,'PRUEBA63')",[JSON.stringify(tallas63)]);
  const rellenado63=await one('select oc,cantidad_pedida from items_orden where id=$1',[blank63]);
  assert.equal(rellenado63.oc,'OC63');assert.equal(rellenado63.cantidad_pedida,7);checks++;
  assert.equal((await one('select oc from items_orden where id=$1',[item63])).oc,'OC63');checks++;
  await exec('RESET ROLE');
  const previos64=(await db.query('select * from movimientos order by id')).rows;
  const fechaSql=readFileSync('sql/pruebas/064_fecha_despacho.sql','utf8');
  await exec(fechaSql); await exec(fechaSql);
  assert.deepEqual((await db.query('select * from movimientos order by id')).rows,previos64);checks++;
  assert.equal((await one('select fecha_ultimo_despacho from vista_kardex where item_orden_id=$1',[sinStock63])).fecha_ultimo_despacho,null);checks++;
  await db.query("insert into movimientos(tipo,item_orden_id,cantidad,ubicacion_id,fecha,admin_correccion_id) values('despacho',$1,1,$2,'2040-01-01',null),('despacho',$1,-1,$2,'2040-01-02',$3),('entrega_produccion',$1,1,null,'2041-01-01',null)",[item63,loc63,correction]);
  const fechas64=await one('select fecha_ultimo_despacho,fecha_ultima_entrega from vista_kardex where item_orden_id=$1',[item63]);
  assert.equal(new Date(fechas64.fecha_ultimo_despacho).toISOString(),'2040-01-01T00:00:00.000Z');checks++;
  assert.equal(new Date(fechas64.fecha_ultima_entrega).toISOString(),'2041-01-01T00:00:00.000Z');checks++;
  console.log(`SQL: ${checks} verificaciones correctas. Base local en memoria; no se accedió a Supabase.`);
} catch (e) {
  console.error({message:e.message, detail:e.detail, where:e.where, position:e.position, checks});
  process.exitCode = 1;
} finally { await db.close(); }
