-- SOLO DEV. Aplicar después de 061. Solo lectura: no cambia datos ni permisos operativos.
BEGIN;
SET LOCAL lock_timeout='5s';
DO $$ BEGIN
 IF to_regclass('public.clientes') IS NOT NULL OR to_regclass('public.devoluciones_cliente') IS NOT NULL THEN RAISE EXCEPTION 'Archivo exclusivo de PRUEBAS.'; END IF;
 IF to_regprocedure('public.wms_nombre_actor()') IS NULL THEN RAISE EXCEPTION 'Aplicar primero 061 en PRUEBAS.'; END IF;
END $$;
CREATE OR REPLACE VIEW public.admin_reporte_movimientos_interno AS
SELECT 'Movimientos:'||movimientos.id::text AS registro, movimientos.fecha AS fecha, coalesce(op.numero_op,'') AS op, coalesce(io.codigo,'') AS codigo, coalesce(io.descripcion,'') AS producto, coalesce(io.talla,'') AS talla, coalesce(op.cliente,'') AS cliente, coalesce(nullif(u.nombre,''),'Sin registrar') AS persona, 'Movimientos'::text AS origen, movimientos.tipo AS tipo, movimientos.cantidad::bigint AS cantidad, ''::text AS causal, ''::text AS contraparte, movimientos.nota::text AS detalle, to_jsonb(movimientos) AS datos_crudos FROM public.movimientos LEFT JOIN public.usuarios u ON u.id=movimientos.usuario_id LEFT JOIN public.items_orden io ON io.id=movimientos.item_orden_id LEFT JOIN public.ordenes_produccion op ON op.id=io.orden_id;
REVOKE ALL ON public.admin_reporte_movimientos_interno FROM PUBLIC,anon,authenticated;
CREATE OR REPLACE VIEW public.admin_reporte_nc_interno AS
SELECT 'Logística:'||devoluciones_produccion.id::text AS registro, devoluciones_produccion.creado_en AS fecha, coalesce(op.numero_op,'') AS op, coalesce(io.codigo,'') AS codigo, coalesce(io.descripcion,'') AS producto, coalesce(io.talla,'') AS talla, coalesce(op.cliente,'') AS cliente, coalesce(nullif(devoluciones_produccion.operario_nombre,''),'Sin registrar') AS persona, 'Logística'::text AS origen, 'Reporte no conforme' AS tipo, devoluciones_produccion.cantidad::bigint AS cantidad, c.nombre::text AS causal, devoluciones_produccion.recibido_de_produccion::text AS contraparte, devoluciones_produccion.nota::text AS detalle, to_jsonb(devoluciones_produccion) AS datos_crudos FROM public.devoluciones_produccion LEFT JOIN public.causales_devolucion c ON c.id=devoluciones_produccion.causal_id LEFT JOIN public.items_orden io ON io.id=devoluciones_produccion.item_orden_id LEFT JOIN public.ordenes_produccion op ON op.id=io.orden_id
UNION ALL
SELECT 'Aliados:'||no_conformes_aliados.id::text AS registro, no_conformes_aliados.fecha_solicitud AS fecha, coalesce(op.numero_op,'') AS op, coalesce(io.codigo,'') AS codigo, coalesce(io.descripcion,'') AS producto, coalesce(io.talla,'') AS talla, coalesce(op.cliente,'') AS cliente, coalesce(nullif(no_conformes_aliados.usuario_produccion_solicitud_nombre,''),'Sin registrar') AS persona, 'Aliados'::text AS origen, 'Envío no conforme a Aliado' AS tipo, no_conformes_aliados.cantidad_solicitada::bigint AS cantidad, c.nombre::text AS causal, no_conformes_aliados.persona_aliado_entrega::text AS contraparte, no_conformes_aliados.nota_solicitud::text AS detalle, to_jsonb(no_conformes_aliados) AS datos_crudos FROM public.no_conformes_aliados LEFT JOIN public.causales_devolucion c ON c.id=no_conformes_aliados.causal_id LEFT JOIN public.items_orden io ON io.id=no_conformes_aliados.item_orden_id LEFT JOIN public.ordenes_produccion op ON op.id=io.orden_id;
REVOKE ALL ON public.admin_reporte_nc_interno FROM PUBLIC,anon,authenticated;
CREATE OR REPLACE VIEW public.admin_reporte_auditoria_interno AS
SELECT 'Movimientos:'||movimientos.id::text AS registro, movimientos.fecha AS fecha, coalesce(op.numero_op,'') AS op, coalesce(io.codigo,'') AS codigo, coalesce(io.descripcion,'') AS producto, coalesce(io.talla,'') AS talla, coalesce(op.cliente,'') AS cliente, coalesce(nullif(u.nombre,''),'Sin registrar') AS persona, 'Movimientos'::text AS origen, movimientos.tipo AS tipo, movimientos.cantidad::bigint AS cantidad, ''::text AS causal, ''::text AS contraparte, movimientos.nota::text AS detalle, to_jsonb(movimientos) AS datos_crudos FROM public.movimientos LEFT JOIN public.usuarios u ON u.id=movimientos.usuario_id LEFT JOIN public.items_orden io ON io.id=movimientos.item_orden_id LEFT JOIN public.ordenes_produccion op ON op.id=io.orden_id
UNION ALL
SELECT 'Logística:'||devoluciones_produccion.id::text AS registro, devoluciones_produccion.creado_en AS fecha, coalesce(op.numero_op,'') AS op, coalesce(io.codigo,'') AS codigo, coalesce(io.descripcion,'') AS producto, coalesce(io.talla,'') AS talla, coalesce(op.cliente,'') AS cliente, coalesce(nullif(devoluciones_produccion.operario_nombre,''),'Sin registrar') AS persona, 'Logística'::text AS origen, 'Reporte no conforme' AS tipo, devoluciones_produccion.cantidad::bigint AS cantidad, c.nombre::text AS causal, devoluciones_produccion.recibido_de_produccion::text AS contraparte, devoluciones_produccion.nota::text AS detalle, to_jsonb(devoluciones_produccion) AS datos_crudos FROM public.devoluciones_produccion LEFT JOIN public.causales_devolucion c ON c.id=devoluciones_produccion.causal_id LEFT JOIN public.items_orden io ON io.id=devoluciones_produccion.item_orden_id LEFT JOIN public.ordenes_produccion op ON op.id=io.orden_id
UNION ALL
SELECT 'Aliados:'||no_conformes_aliados.id::text AS registro, no_conformes_aliados.fecha_solicitud AS fecha, coalesce(op.numero_op,'') AS op, coalesce(io.codigo,'') AS codigo, coalesce(io.descripcion,'') AS producto, coalesce(io.talla,'') AS talla, coalesce(op.cliente,'') AS cliente, coalesce(nullif(no_conformes_aliados.usuario_produccion_solicitud_nombre,''),'Sin registrar') AS persona, 'Aliados'::text AS origen, 'Envío no conforme a Aliado' AS tipo, no_conformes_aliados.cantidad_solicitada::bigint AS cantidad, c.nombre::text AS causal, no_conformes_aliados.persona_aliado_entrega::text AS contraparte, no_conformes_aliados.nota_solicitud::text AS detalle, to_jsonb(no_conformes_aliados) AS datos_crudos FROM public.no_conformes_aliados LEFT JOIN public.causales_devolucion c ON c.id=no_conformes_aliados.causal_id LEFT JOIN public.items_orden io ON io.id=no_conformes_aliados.item_orden_id LEFT JOIN public.ordenes_produccion op ON op.id=io.orden_id
UNION ALL
SELECT 'Producción:'||lote_items.id::text AS registro, l.fecha_envio AS fecha, coalesce(op.numero_op,'') AS op, coalesce(io.codigo,'') AS codigo, coalesce(io.descripcion,'') AS producto, coalesce(io.talla,'') AS talla, coalesce(op.cliente,'') AS cliente, coalesce(nullif(l.operario_nombre,''),'Sin registrar') AS persona, 'Producción'::text AS origen, 'Entrega de lote' AS tipo, lote_items.cantidad_enviada::bigint AS cantidad, ''::text AS causal, ''::text AS contraparte, l.numero::text AS detalle, to_jsonb(lote_items) AS datos_crudos FROM public.lote_items JOIN public.lotes l ON l.id=lote_items.lote_id LEFT JOIN public.items_orden io ON io.id=lote_items.item_orden_id LEFT JOIN public.ordenes_produccion op ON op.id=io.orden_id
UNION ALL
SELECT 'Recepción:'||lote_items.id::text AS registro, lote_items.fecha_recepcion AS fecha, coalesce(op.numero_op,'') AS op, coalesce(io.codigo,'') AS codigo, coalesce(io.descripcion,'') AS producto, coalesce(io.talla,'') AS talla, coalesce(op.cliente,'') AS cliente, coalesce(nullif(lote_items.recibido_por,''),'Sin registrar') AS persona, 'Recepción'::text AS origen, 'Última recepción acumulada' AS tipo, lote_items.cantidad_recibida::bigint AS cantidad, ''::text AS causal, ''::text AS contraparte, coalesce(lote_items.novedad,'')::text AS detalle, to_jsonb(lote_items) AS datos_crudos FROM public.lote_items  LEFT JOIN public.items_orden io ON io.id=lote_items.item_orden_id LEFT JOIN public.ordenes_produccion op ON op.id=io.orden_id WHERE lote_items.fecha_recepcion IS NOT NULL
UNION ALL
SELECT 'Liberaciones:'||liberaciones_no_conforme.id::text AS registro, liberaciones_no_conforme.creado_en AS fecha, coalesce(op.numero_op,'') AS op, coalesce(io.codigo,'') AS codigo, coalesce(io.descripcion,'') AS producto, coalesce(io.talla,'') AS talla, coalesce(op.cliente,'') AS cliente, coalesce(nullif(liberaciones_no_conforme.operario_nombre,''),'Sin registrar') AS persona, 'Liberaciones'::text AS origen, 'Liberación no conforme' AS tipo, liberaciones_no_conforme.cantidad::bigint AS cantidad, ''::text AS causal, liberaciones_no_conforme.recibido_por_logistica::text AS contraparte, liberaciones_no_conforme.nota::text AS detalle, to_jsonb(liberaciones_no_conforme) AS datos_crudos FROM public.liberaciones_no_conforme  LEFT JOIN public.items_orden io ON io.id=liberaciones_no_conforme.item_orden_id LEFT JOIN public.ordenes_produccion op ON op.id=io.orden_id
UNION ALL
SELECT 'Liberaciones Aliados:'||liberaciones_aliados.id::text AS registro, liberaciones_aliados.fecha AS fecha, coalesce(op.numero_op,'') AS op, coalesce(io.codigo,'') AS codigo, coalesce(io.descripcion,'') AS producto, coalesce(io.talla,'') AS talla, coalesce(op.cliente,'') AS cliente, coalesce(nullif(liberaciones_aliados.usuario_produccion_nombre,''),'Sin registrar') AS persona, 'Liberaciones Aliados'::text AS origen, 'Liberación Aliado' AS tipo, liberaciones_aliados.cantidad::bigint AS cantidad, ''::text AS causal, liberaciones_aliados.persona_aliado_libera::text AS contraparte, liberaciones_aliados.nota::text AS detalle, to_jsonb(liberaciones_aliados) AS datos_crudos FROM public.liberaciones_aliados LEFT JOIN public.no_conformes_aliados s ON s.id=liberaciones_aliados.solicitud_id LEFT JOIN public.items_orden io ON io.id=s.item_orden_id LEFT JOIN public.ordenes_produccion op ON op.id=io.orden_id
UNION ALL
SELECT 'Sobrantes:'||sobrantes_bodega.id::text AS registro, sobrantes_bodega.fecha AS fecha, coalesce(op.numero_op,'') AS op, coalesce(io.codigo,'') AS codigo, coalesce(io.descripcion,'') AS producto, coalesce(io.talla,'') AS talla, coalesce(op.cliente,'') AS cliente, coalesce(nullif(sobrantes_bodega.operario_nombre,''),'Sin registrar') AS persona, 'Sobrantes'::text AS origen, 'Registro sobrante' AS tipo, sobrantes_bodega.cantidad::bigint AS cantidad, ''::text AS causal, ''::text AS contraparte, sobrantes_bodega.nota::text AS detalle, to_jsonb(sobrantes_bodega) AS datos_crudos FROM public.sobrantes_bodega  LEFT JOIN public.items_orden io ON io.id=sobrantes_bodega.item_orden_id LEFT JOIN public.ordenes_produccion op ON op.id=io.orden_id
UNION ALL
SELECT 'Resoluciones:'||sobrantes_bodega.id::text AS registro, sobrantes_bodega.fecha_resolucion AS fecha, coalesce(op.numero_op,'') AS op, coalesce(io.codigo,'') AS codigo, coalesce(io.descripcion,'') AS producto, coalesce(io.talla,'') AS talla, coalesce(op.cliente,'') AS cliente, coalesce(nullif('Sin registrar',''),'Sin registrar') AS persona, 'Resoluciones'::text AS origen, 'Resolución sobrante' AS tipo, NULL::bigint::bigint AS cantidad, ''::text AS causal, ''::text AS contraparte, coalesce(sobrantes_bodega.resolucion,'')::text AS detalle, to_jsonb(sobrantes_bodega) AS datos_crudos FROM public.sobrantes_bodega  LEFT JOIN public.items_orden io ON io.id=sobrantes_bodega.item_orden_id LEFT JOIN public.ordenes_produccion op ON op.id=io.orden_id WHERE sobrantes_bodega.fecha_resolucion IS NOT NULL
UNION ALL
SELECT 'Correcciones:'||admin_correcciones.id::text AS registro, admin_correcciones.fecha AS fecha, coalesce(op.numero_op,'') AS op, coalesce(io.codigo,'') AS codigo, coalesce(io.descripcion,'') AS producto, coalesce(io.talla,'') AS talla, coalesce(op.cliente,'') AS cliente, coalesce(nullif(admin_correcciones.actor,''),'Sin registrar') AS persona, 'Correcciones'::text AS origen, 'Corrección: '||admin_correcciones.campo AS tipo, NULL::bigint::bigint AS cantidad, ''::text AS causal, ''::text AS contraparte, admin_correcciones.motivo::text AS detalle, to_jsonb(admin_correcciones) AS datos_crudos FROM public.admin_correcciones  LEFT JOIN public.items_orden io ON io.id=admin_correcciones.item_id LEFT JOIN public.ordenes_produccion op ON op.id=io.orden_id
UNION ALL
SELECT 'Catálogos:'||admin_catalogos_historial.id::text AS registro, admin_catalogos_historial.fecha AS fecha, coalesce(op.numero_op,'') AS op, coalesce(io.codigo,'') AS codigo, coalesce(io.descripcion,'') AS producto, coalesce(io.talla,'') AS talla, coalesce(op.cliente,'') AS cliente, coalesce(nullif(u.nombre,''),'Sin registrar') AS persona, 'Catálogos'::text AS origen, 'Cambio catálogo: '||admin_catalogos_historial.catalogo AS tipo, NULL::bigint::bigint AS cantidad, ''::text AS causal, ''::text AS contraparte, admin_catalogos_historial.registro_id::text::text AS detalle, to_jsonb(admin_catalogos_historial) AS datos_crudos FROM public.admin_catalogos_historial LEFT JOIN public.usuarios u ON u.auth_id=admin_catalogos_historial.actor_id LEFT JOIN public.items_orden io ON io.id=NULL::uuid LEFT JOIN public.ordenes_produccion op ON op.id=io.orden_id
UNION ALL
SELECT 'Importación Excel:'||admin_importaciones.id::text AS registro, admin_importaciones.fecha AS fecha, coalesce(op.numero_op,'') AS op, coalesce(io.codigo,'') AS codigo, coalesce(io.descripcion,'') AS producto, coalesce(io.talla,'') AS talla, coalesce(op.cliente,'') AS cliente, coalesce(nullif(u.nombre,''),'Sin registrar') AS persona, 'Importación Excel'::text AS origen, 'Importar tabla: '||admin_importaciones.vista AS tipo, NULL::bigint::bigint AS cantidad, ''::text AS causal, ''::text AS contraparte, admin_importaciones.motivo::text AS detalle, to_jsonb(admin_importaciones)-'archivo' AS datos_crudos FROM public.admin_importaciones LEFT JOIN public.usuarios u ON u.auth_id=admin_importaciones.actor_id LEFT JOIN public.items_orden io ON io.id=NULL::uuid LEFT JOIN public.ordenes_produccion op ON op.id=io.orden_id
UNION ALL
SELECT 'Importación ERP:'||importaciones.id::text AS registro, importaciones.creado_en AS fecha, coalesce(op.numero_op,'') AS op, coalesce(io.codigo,'') AS codigo, coalesce(io.descripcion,'') AS producto, coalesce(io.talla,'') AS talla, coalesce(op.cliente,'') AS cliente, coalesce(nullif(importaciones.usuario_nombre,''),'Sin registrar') AS persona, 'Importación ERP'::text AS origen, 'Importar ERP' AS tipo, NULL::bigint::bigint AS cantidad, ''::text AS causal, ''::text AS contraparte, importaciones.nombre_archivo::text AS detalle, to_jsonb(importaciones) AS datos_crudos FROM public.importaciones  LEFT JOIN public.items_orden io ON io.id=NULL::uuid LEFT JOIN public.ordenes_produccion op ON op.id=io.orden_id;
REVOKE ALL ON public.admin_reporte_auditoria_interno FROM PUBLIC,anon,authenticated;

CREATE OR REPLACE FUNCTION public.admin_reporte_pagina(p_tipo text, p_despues text DEFAULT '', p_corte timestamptz DEFAULT now())
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public SET statement_timeout='30s' AS $$
DECLARE tabla text; resultado jsonb;
BEGIN
 IF NOT public.admin_es_admin() THEN RAISE EXCEPTION 'Acceso exclusivo del administrador.' USING ERRCODE='42501'; END IF;
 IF p_corte IS NULL OR p_despues IS NULL THEN RAISE EXCEPTION 'Paginación inválida.'; END IF;
 tabla:=CASE p_tipo WHEN 'movimientos' THEN 'admin_reporte_movimientos_interno' WHEN 'nc' THEN 'admin_reporte_nc_interno' WHEN 'auditoria' THEN 'admin_reporte_auditoria_interno' END;
 IF tabla IS NULL THEN RAISE EXCEPTION 'Reporte inválido.'; END IF;
 EXECUTE format('SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY registro),''[]''::jsonb) FROM (SELECT * FROM public.%I WHERE registro > $1 AND fecha <= $2 ORDER BY registro LIMIT 1000) t',tabla)
 INTO resultado USING p_despues,p_corte;
 RETURN resultado;
END $$;
CREATE OR REPLACE FUNCTION public.admin_reporte_resumen() RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public SET statement_timeout='30s' AS $$
DECLARE resultado jsonb; hoy date:=(now() AT TIME ZONE 'America/Bogota')::date;
BEGIN
 IF NOT public.admin_es_admin() THEN RAISE EXCEPTION 'Acceso exclusivo del administrador.' USING ERRCODE='42501'; END IF;
 SELECT jsonb_build_object(
  'op_activas', count(DISTINCT numero_op) FILTER (WHERE cantidad_pedida>despachado OR pendiente_reproceso>0 OR pendiente_aliados>0),
  'op_atrasadas',count(DISTINCT numero_op) FILTER (WHERE (fecha_esperada_produccion<hoy AND cantidad_pedida>producido) OR (fecha_esperada_logistica<hoy AND cantidad_pedida>despachado)),
  'op_no_conforme',count(DISTINCT numero_op) FILTER (WHERE pendiente_reproceso>0 OR pendiente_aliados>0),
  'sobrantes_pendientes',(SELECT count(*) FROM public.sobrantes_bodega WHERE estado='pendiente'),
  'unidades_sobrantes',(SELECT coalesce(sum(cantidad),0) FROM public.sobrantes_bodega WHERE estado='pendiente'),
  'actualizado_en',now()) INTO resultado FROM public.vista_kardex WHERE admin_eliminado_en IS NULL;
 RETURN resultado;
END $$;
REVOKE ALL ON FUNCTION public.admin_reporte_pagina(text,text,timestamptz),public.admin_reporte_resumen() FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.admin_reporte_pagina(text,text,timestamptz),public.admin_reporte_resumen() TO authenticated;
NOTIFY pgrst,'reload schema';
COMMIT;
